import {
  Card,
  Col,
  Container,
  Image,
  Link,
  Row,
  Spacer,
  Text,
} from '@nextui-org/react'
import Head from 'next/head'
import { ReactElement, useEffect, useState } from 'react'
import { cloudAgentUrl } from '../constants'

export default function Layout({ children }: { children: ReactElement }) {
  const [did, setDid] = useState('')

  useEffect(() => {
    // setLoading(true)
    fetch(`${cloudAgentUrl}/did`)
      .then((res) => res.json())
      .then((data) => {
        setDid(data.did)
        // setLoading(false)
      })
  }, [])

  return (
    <Container display="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card css={{ $$cardColor: '$colors$gradient' }}>
        <Card.Body>
          <Row justify="space-between" align="center">
            <Col span={3}>
              <Image
                width={300}
                height={79}
                src="/HL_GlobalForum_2022_PromoGraphics_Logo-White.svg"
                alt="Default Image"
                objectFit="cover"
              />
            </Col>
            <Col span={3}>
              <Text h6 size={15} color="white" css={{ m: 0 }}>
                Public DID: {did}
              </Text>
              <Text h6 size={15} color="white" css={{ m: 0 }}>
                Credential Definition ID: <Link href="#">Register</Link>
              </Text>
            </Col>
          </Row>
        </Card.Body>
      </Card>
      <Spacer y={1} />
      {children}
    </Container>
  )
}
